Enable wg connection failover and tang binding (#78)
* Enhance wireguard and pbs_storage roles

* Fix linting

- wg VPN connections use now DynDNS 
- Automatic tang binding and disk decryption works fine now

diff --git a/ansible/roles/pbs_storage/templates/disk-decrypt.sh.j2 b/ansible/roles/pbs_storage/templates/disk-decrypt.sh.j2
--- a/ansible/roles/pbs_storage/templates/disk-decrypt.sh.j2
+++ b/ansible/roles/pbs_storage/templates/disk-decrypt.sh.j2
@@ -1,9 +1,6 @@
 #!/bin/bash
-# Dynamically generated by Ansible
+# Generated by Ansible
 set -e
-
-LOGFILE="/var/log/disk-decrypt.log"
-exec > >(ts '[%Y-%m-%d %H:%M:%S]' | tee -a "$LOGFILE") 2>&1
 
 DEVICE="{{ vault_disk_device }}"
 MAPPER_NAME="{{ vault_mapper_name }}"
@@ -13,33 +10,34 @@ EMAIL="{{ vault_admin_email | default('root@localhost') }}"
 
 send_error_email() {
   local subject="Disk-Decrypt Error on $(hostname)"
-  mail -s "$subject" "$EMAIL" < "$LOGFILE"
+  journalctl -u disk-decrypt.service -n 50 | mail -s "$subject" "$EMAIL"
 }
 
-ansible.builtin.systemctl restart systemd-resolved || true
+echo "<6>Starting disk decryption process..."
 
-# Assuming wireguard connection already established with Ansible wireguard playbook
-if ! ping -c1 -W2 "$TANG_SERVER" &>/dev/null; then
-  echo "ERROR: Tang server $TANG_SERVER unreachable!"
+systemctl restart systemd-resolved || true
+
+if ! curl -sfg "https://$TANG_SERVER/adv" &>/dev/null; then
+  echo "<3>ERROR: Tang advertisements at $TANG_SERVER/adv unreachable or invalid!"
   send_error_email
   exit 1
 fi
 
 if [ ! -b "/dev/mapper/$MAPPER_NAME" ]; then
-    echo "Decrypting $DEVICE..."
+    echo "<6>Decrypting $DEVICE..."
     if ! clevis luks unlock -d "$DEVICE" -n "$MAPPER_NAME"; then
-      echo "ERROR: Decryption failed!"
+      echo "<3>ERROR: Decryption failed!"
       send_error_email
       exit 1
     fi
 else
-    echo "Device already decrypted (Mapper $MAPPER_NAME active)."
+    echo "<5>Device already decrypted (Mapper $MAPPER_NAME active)."
 fi
 
 if ! zpool list "$POOL_NAME" &>/dev/null; then
-    echo "Importing ZFS Pool $POOL_NAME..."
+    echo "<6>Importing ZFS Pool $POOL_NAME..."
     if ! zpool import -d /dev/mapper "$POOL_NAME"; then
-      echo "ERROR: Failed to import ZFS pool $POOL_NAME"
+      echo "<3>ERROR: Failed to import ZFS pool $POOL_NAME"
       send_error_email
       exit 1
     fi
@@ -47,4 +45,4 @@ fi
 
 systemctl start proxmox-backup.service proxmox-backup-proxy.service
 
-echo "Unlock and Import successful."
+echo "<5>Unlock and Import successful."
