56 migrate to new architecture (#57)
* Update proxmox modules and tf variable management

Refactor tf variable management with VLANs, IP generation, etc.
Add VLAN support for PROXMOX modules
Add IPv6 support for PROXMOX VM module
Update tofu apply in main workflow

* Extend proxmox vm module for and fix small errors

* Enable conditional forwarding for custom domain

* Update pihole role for conditional forwarding

* Rewrite update playbook

* Add support for searchdomain,nameservers in Proxmox Modules

* Fix Ansible linting errors

* Update pre-commit for .enc file decryption

* Update .sops.yaml for support tfvars encryption from /opentofu

* Update pre-commit logic

diff --git a/scripts/githooks/pre-commit b/scripts/githooks/pre-commit
--- a/scripts/githooks/pre-commit
+++ b/scripts/githooks/pre-commit
@@ -4,9 +4,9 @@ PROJECT_ROOT=$(git rev-parse --show-toplevel)
 CONFIG_PATH="$PROJECT_ROOT/.sops.yaml"
 
 encrypt_files() {
-    local rel_dir=$1      # Relative path from project root
-    local extension=$2    # File extension (e.g., tfvars or jwk)
-    local sops_type=$3     # SOPS data type (e.g., dotenv or json)
+    local rel_dir=$1
+    local extension=$2
+    local sops_type=$3
 
     if [ ! -d "$PROJECT_ROOT/$rel_dir" ]; then
         echo "Info: Directory $rel_dir does not exist. Skipping..."
@@ -15,27 +15,46 @@ encrypt_files() {
 
     for file in "$PROJECT_ROOT/$rel_dir"/*."$extension"; do
         [ -e "$file" ] || continue
-        
+
+        target_file="$file.enc"
         filename=$(basename "$file")
-        
-        # Skip files that are already encrypted
+
+        # Skip already encrypted files
         if [[ "$filename" == *.enc ]]; then
             continue
         fi
 
-        echo "Protecting file: $rel_dir/$filename (Type: $sops_type)"
-        
-        sops --encrypt \
+        # Check for empty source files
+        if [ ! -s "$file" ]; then
+            echo "ERROR: Skipping empty file $filename."
+            exit 1
+        fi
+
+        # only encrypt when timestamp of source file is newer than the encrypted version (target_file)
+        if [ -f "$target_file" ] && [ "$file" -ot "$target_file" ]; then
+            echo "No changes in $filename. No need to encrypt again."
+            continue
+        fi
+
+        echo "Encrypting file: $rel_dir/$filename (Type: $sops_type)"
+
+
+        if sops --encrypt \
              --config "$CONFIG_PATH" \
              --input-type "$sops_type" \
              --output-type "$sops_type" \
-             "$file" > "$PROJECT_ROOT/$rel_dir/$filename.enc"
-        
-        git add "$PROJECT_ROOT/$rel_dir/$filename.enc"
+             --output "$target_file" \
+             "$file"; then
+
+            git add "$target_file"
+        else
+            echo "ERROR: Encryption failed for $filename. Check your .sops.yaml!"
+            exit 1
+        fi
     done
 }
 
-encrypt_files "opentofu/infra" "tfvars" "dotenv"
+encrypt_files "opentofu" "tfvars" "dotenv"
 encrypt_files "ansible/roles/tang/files/tang-keys" "jwk" "json"
 
 
