Update workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -116,15 +116,16 @@ jobs:
           ansible-playbook -i inventory.ini infra_playbook.yml > "$LOG_FILE" 2>&1
         continue-on-error: false
 
-      - name: Display Play Recap Only
-        if: always()
+      - name: Display Ansible PLAY RECAP
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         run: |
           echo "====================================================================="
-          grep -A 100 "PLAY RECAP" "${{ env.ANSIBLE_LOG_PATH }}" || echo "PLAY RECAP not found."
+          sed -n '/PLAY RECAP/,$p' "${{ env.ANSIBLE_LOG_PATH }}" || echo "PLAY RECAP not found."
           echo "====================================================================="
 
-      - name: Upload Detailed Ansible Log
-        if: always()
+      - name: Upload Ansible Log
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+        run: |
         uses: actions/upload-artifact@v4
         with:
           name: ansible-detailed-log-run-${{ github.run_number }}
diff --git a/.github/workflows/upgrade.yml b/.github/workflows/upgrade.yml
--- a/.github/workflows/upgrade.yml
+++ b/.github/workflows/upgrade.yml
@@ -74,11 +74,11 @@ jobs:
           ansible-playbook -i inventory.ini apt_upgrade_playbook.yml --tags repair > "$LOG_FILE" 2>&1
         continue-on-error: false
 
-      - name: Display Play Recap Only
+      - name: Display Ansible PLAY RECAP
         if: always()
         run: |
           echo "====================================================================="
-          grep -A 100 "PLAY RECAP" "${{ env.ANSIBLE_LOG_PATH }}" || echo "PLAY RECAP not found."
+          sed -n '/PLAY RECAP/,$p' "${{ env.ANSIBLE_LOG_PATH }}" || echo "PLAY RECAP not found."
           echo "====================================================================="
 
       - name: Upload Detailed Ansible Log
