Upgrade ansible logging in workflows (#92)
* Upgrade ansible logging in workflows

* Update workflows

* Fix workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -110,7 +110,26 @@ jobs:
         working-directory: ${{ env.ANSIBLE_WORKING_DIR }}
         run: |
           export ANSIBLE_HOST_KEY_CHECKING=False
-          ansible-playbook -i inventory.ini infra_playbook.yml
+          LOG_FILE="ansible_run_${{ github.run_number }}_id_${{ github.run_id }}.log"
+          echo "ANSIBLE_LOG_PATH=${LOG_FILE}" >> $GITHUB_ENV
+
+          ansible-playbook -i inventory.ini infra_playbook.yml > "$LOG_FILE" 2>&1
+        continue-on-error: false
+
+      - name: Display Ansible PLAY RECAP
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+        run: |
+          echo "====================================================================="
+          sed -n '/PLAY RECAP/,$p' "${{ env.ANSIBLE_LOG_PATH }}" || echo "PLAY RECAP not found."
+          echo "====================================================================="
+
+      - name: Upload Ansible Log
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+        uses: actions/upload-artifact@v4
+        with:
+          name: ansible-detailed-log-run-${{ github.run_number }}
+          path: ${{ env.ANSIBLE_LOG_PATH }}
+          retention-days: 7
 
       - name: Send XMPP Notification
         if: always()
diff --git a/.github/workflows/upgrade.yml b/.github/workflows/upgrade.yml
--- a/.github/workflows/upgrade.yml
+++ b/.github/workflows/upgrade.yml
@@ -55,7 +55,7 @@ jobs:
 
       - name: OpenTofu Generate inventory.ini
         working-directory: ${{ env.OPENTOFU_WORKING_DIR }}
-        run: tofu apply -target=local_file.ansible_inventory -replace=local_file.ansible_inventory -auto-approve -lock=false
+        run: tofu apply -var-file="../shared.tfvars" -target=local_file.ansible_inventory -replace=local_file.ansible_inventory -auto-approve -lock=false
 
       - name: Install SSH Private Key
         uses: shimataro/ssh-key-action@v2
@@ -68,4 +68,23 @@ jobs:
         working-directory: ${{ env.ANSIBLE_WORKING_DIR }}
         run: |
           export ANSIBLE_HOST_KEY_CHECKING=False
-          ansible-playbook -i inventory.ini apt_upgrade_playbook.yml --tags repair
+          LOG_FILE="ansible_run_${{ github.run_number }}_id_${{ github.run_id }}.log"
+          echo "ANSIBLE_LOG_PATH=${LOG_FILE}" >> $GITHUB_ENV
+
+          ansible-playbook -i inventory.ini apt_upgrade_playbook.yml --tags repair > "$LOG_FILE" 2>&1
+        continue-on-error: false
+
+      - name: Display Ansible PLAY RECAP
+        if: always()
+        run: |
+          echo "====================================================================="
+          sed -n '/PLAY RECAP/,$p' "${{ env.ANSIBLE_LOG_PATH }}" || echo "PLAY RECAP not found."
+          echo "====================================================================="
+
+      - name: Upload Detailed Ansible Log
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: ansible-detailed-log-run-${{ github.run_number }}
+          path: ${{ env.ANSIBLE_LOG_PATH }}
+          retention-days: 7
